### PR TITLE
Java 8 upgrade

### PR DESCRIPTION
**Pull request by remmeier**
with minor generic compile fixes

### CODE REVIEW

**Comment by chb0github** [comment]
So, does this mean we are finally ready to create 3.0 with java 8? This can't go into the 2.8.x branch

**Comment by remmeier** [comment]
I would say so, not? among all the cleanup, that is probably the smallest one...

**Comment by remmeier** [comment]
applied https://github.com/katharsis-project/katharsis-framework/pull/284, which seems to have gone into the master branch by accident

**Comment by chb0github** [comment]
@remmeier Ok, I am waiting to hear from @masterspambot

**Comment by remmeier** [comment]
somehow I think this upgrade still seems to be a bit early unfortunately. I got one new project which is still forced to use the JEE 7 / Java 7 stack but would be interested in using Katharasis. So I'm closing this for now as we do not really suffer from not being able to use the Lambdas. I think community growth is better than the latest Java features. Maybe we could also consider a katharsis-java9 project or something should we have something where we really benefit from newer java versions.

**Pull request closed without merging**
