### PR TITLE
Add katharsis client and JPA feature

### LINKED ISSUE #26: Add jsonapi client
_From @ieugen on May 18, 2016 11:51_

Katharsis implements the server side of things. It would be nice to also have a jsonapi client.

One use case is to write integration tests. I imagine that it would not be a big win (since we might reuse most of the code and if we have implemented something wrong it will work because of code sharing).

_Copied from original issue: katharsis-project/katharsis-core#315_

### PR DESCRIPTION
**Pull request by ieugen**
* fixes #26 - json api client
* usefull for #53 - json api serializtion/deserialization

### CODE REVIEW

**Comment by remmeier** [comment]
did not see this PR. Created a first PR myself to include some changes done to katharsis-core. Two, three more will follow.  In the progress I will resolve all the conflicts (I was still on master). After that it should be very easy to add the new modules like katharsis-client and katharsis-jpa.

**Comment by ieugen** [comment]
@remmeier : this has conflicts so we can't merge. Since this is a repo on you account I can't help a lot. 

Olso we need to focus on API cleanup to make bug fixing easier and code more maintainable. New features are not a good idea right now because we will have a lot more API that can break and that we need to update. If you have some time, please give a hand on the refactoring.

**Comment by remmeier** [comment]
I think we can close this one, I do smaller PRs instead.

**Comment by ieugen** [comment]
Even better. I can do review so we can merge them, just ping me.

**Pull request closed without merging**
