### PR TITLE
Send Accept header on client API calls

### PR DESCRIPTION
**Pull request by csetera**
As discussed in https://github.com/katharsis-project/katharsis-framework/issues/117#issuecomment-246190999

### CODE REVIEW

**Comment by csetera** [comment]
I will try to find some time.

**Comment by csetera** [comment]
Looking at this, I'm not entirely sure how to test accept headers?  It looks like all of this boils down to standard JAX-RS calls via the KatharsisFeature?  I'm happy to add some tests if someone points me in the right direction.

**Comment by chb0github** [comment]
The way to test this is to fire off a basic http server as part of the
test. Look at the jersey example. Then in the server, assert that the
accept header is correct

**Comment by csetera** [comment]
I just pushed updates to support validating request headers.  I know they are in our forked repo, but not sure if they automatically show up in this pull request?  (Seems like, but if not please let me know).

**Comment by remmeier** [comment]
can we updated the pr? then I merge it in.

**Comment by csetera** [comment]
I apologize for being a newbie on this.  Can you tell me what is necessary to update the PR?  I was under the impression it was "automatic", but if you tell me what I need to do (or point me to appropriate documentation), I'm happy to do what is necessary.

**Comment by chb0github** [comment]
All you need to do is push to the fork/branch you used for the pr and its
automatic

**Comment by csetera** [comment]
Somehow, I must have done something wrong?  I made this change and pushed it to my fork 18 days ago (see https://github.com/Baseventure/katharsis-framework/commit/f37783a03e5f718e5228ffa9f18f1fff2d8700da) .  Is there a step I'm missing here?

**Comment by chb0github** [comment]
Look for me on gitter later

**Comment by csetera** [comment]
I think I finally got this straightened out.  Please let me know if there is anything else I need to do.

**Comment by remmeier** [comment]
builds looks ok, sonar setup issues in the build, applying the PR anyway.

**Pull request merged**
