### PR TITLE
katharsis-servlet: use utf-8 when decoding request body

### PR DESCRIPTION
**Pull request by robertgrabowski**
This fix makes KatharsisInvoker.inputStreamToBody() use UTF-8 when reading the HTTP request body. While AbstractKatharsisServlet.service() already sets the character encoding on the HttpServletRequest to UTF-8, this has no effect when reading the request body, because it is read with a Scanner from an InputStream.

I also added 
- a test which shows that sending a POST request to create a resource indeed returns the created resource 
- another test which temporarily sets "ISO-8859-1" as the system default encoding, creates a resource with Chinese attribute values and expects that the returned resource contains the correct attribute values (which shows that the default encoding is ignored)

### CODE REVIEW

**Comment by robertgrabowski** [comment]
All tests failed due to unrelated infrastructure problem (could not contact oracle.com to download JDK 8). Hope this comment triggers a new build at Travis CI.

**Comment by robertgrabowski** [comment]
Closing and re-opening the pull request successfully re-triggered the build on Travis CI. All unit tests pass now. 

The build still fails, because it tries to deploy the katharsis parent POM unsuccessfully. Apparently, `build.sh` is trying to prevent this for pull request builds with the following condition
```
if [ "${TRAVIS_PULL_REQUEST}" != "true" ]
```
but it does not work as intended: According to the [Travis CI doc](https://docs.travis-ci.com/user/environment-variables/#Convenience-Variables), `$TRAVIS_PULL_REQUEST` contains the number of the pull request, or `false` if this is no pull request, but never `true`.

**Comment by chb0github** [comment]
I am a proponent of ditching the build file all together and just using
maven directly

**Comment by Ramblurr** [comment]
@robertgrabowski  Could you please update the PR with the latest changes from develop?

**Comment by robertgrabowski** [comment]
@Ramblurr I have updated the PR with the latest changes from the base branch 'develop'. 

The overall build still fails in the last phase due to the unrelated problem with 'build.sh' that I mentioned in my comment on Nov 11 (it tries to deploy the parent POM even though it's a pull request). The build of the actual artifacts and the unit tests go through just fine.

**Comment by chb0github** [comment]
I would like to merge this. I assume it builds and runs tests fine

**Comment by Ramblurr** [comment]
I'd like to merge I too. But I would also like to fix the build issue. I'll run test locally to make sure it works as advertised :) then we can merge it.

**Comment by chb0github** [comment]
I guess I might need to get involved in fixing the build. Can you post the
error here?

**Comment by Ramblurr** [comment]
The travis build error is [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/184561758/log.txt)

```
[INFO] Reactor Summary:
[INFO] 
[INFO] Katharsis parent POM ............................... SUCCESS [  0.994 s]
[INFO] katharsis-core ..................................... SUCCESS [ 32.425 s]
[INFO] katharsis-rs ....................................... SUCCESS [ 14.141 s]
[INFO] io.katharsis:katharsis-servlet ..................... SUCCESS [  6.253 s]
[INFO] katharsis-cdi ...................................... SUCCESS [  5.579 s]
[INFO] katharsis-spring ................................... SUCCESS [  1.784 s]
[INFO] katharsis-vertx .................................... SUCCESS [  1.030 s]
[INFO] katharsis-client ................................... SUCCESS [ 32.385 s]
[INFO] katharsis-jpa ...................................... SUCCESS [ 48.712 s]
[INFO] katharsis-validation ............................... SUCCESS [ 10.588 s]
[INFO] katharsis-brave .................................... SUCCESS [  9.919 s]
[INFO] katharsis-examples ................................. SUCCESS [  0.008 s]
[INFO] Katharsis Dropwizard + MongoDB Example ............. SUCCESS [  5.244 s]
[INFO] Katharsis Jersey Example ........................... SUCCESS [  4.100 s]
[INFO] Katharsis Simple Dropwizard Example ................ SUCCESS [  2.828 s]
[INFO] Katharsis Wildfly Example .......................... SUCCESS [  1.067 s]
[INFO] Spring Boot Simple Example ......................... SUCCESS [ 18.521 s]
[INFO] Katharsis Vertx Simple Example ..................... SUCCESS [  0.642 s]
[INFO] katharsis-ui ....................................... SUCCESS [  0.079 s]
[INFO] Katharsis build POM ................................ SUCCESS [  5.213 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:24 min
[INFO] Finished at: 2016-12-16T15:31:48+00:00
[INFO] Final Memory: 101M/445M
[INFO] ------------------------------------------------------------------------
if [ "${TRAVIS_PULL_REQUEST}" != "true" ] && [ "$(git status | head -1)" != "HEAD detached at FETCH_HEAD" ] ; then

    if [[ $TRAVIS_BRANCH == 'master' ]]; then
      # deploy to staging repository
      echo "TODO: ADD DEPLOYMENT TO STAGING REPOSITORY"
    elif [[ $TRAVIS_BRANCH == 'develop' ]]; then
      mvn clean deploy -DskipTests=true --settings settings.xml
    else
      mvn clean install -DskipTests=true --settings settings.xml
    fi
fi
git status | head -1)"
git status | head -1)
git status | head -1
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.katharsis:katharsis-parent:pom:2.8.2-SNAPSHOT
[WARNING] 'parent.relativePath' points at io.katharsis:katharsis-build instead of org.sonatype.oss:oss-parent, please verify your project structure @ line 68, column 13
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.katharsis:katharsis-core:bundle:2.8.2-SNAPSHOT
[WARNING] 'parent.relativePath' of POM io.katharsis:katharsis-parent:2.8.2-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml) points at io.katharsis:katharsis-build instead of org.sonatype.oss:oss-parent, please verify your project structure @ io.katharsis:katharsis-parent:2.8.2-SNAPSHOT, /home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml, line 68, column 13
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.katharsis:katharsis-rs:bundle:2.8.2-SNAPSHOT
[WARNING] 'parent.relativePath' of POM io.katharsis:katharsis-parent:2.8.2-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml) points at io.katharsis:katharsis-build instead of org.sonatype.oss:oss-parent, please verify your project structure @ io.katharsis:katharsis-parent:2.8.2-SNAPSHOT, /home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml, line 68, column 13
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.katharsis:katharsis-servlet:bundle:2.8.2-SNAPSHOT
[WARNING] 'parent.relativePath' of POM io.katharsis:katharsis-parent:2.8.2-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml) points at io.katharsis:katharsis-build instead of org.sonatype.oss:oss-parent, please verify your project structure @ io.katharsis:katharsis-parent:2.8.2-SNAPSHOT, /home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml, line 68, column 13
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.katharsis:katharsis-cdi:bundle:2.8.2-SNAPSHOT
[WARNING] 'parent.relativePath' of POM io.katharsis:katharsis-parent:2.8.2-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml) points at io.katharsis:katharsis-build instead of org.sonatype.oss:oss-parent, please verify your project structure @ io.katharsis:katharsis-parent:2.8.2-SNAPSHOT, /home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml, line 68, column 13
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.katharsis:katharsis-spring:bundle:2.8.2-SNAPSHOT
[WARNING] 'parent.relativePath' of POM io.katharsis:katharsis-parent:2.8.2-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml) points at io.katharsis:katharsis-build instead of org.sonatype.oss:oss-parent, please verify your project structure @ io.katharsis:katharsis-parent:2.8.2-SNAPSHOT, /home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml, line 68, column 13
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.katharsis:katharsis-vertx:bundle:2.8.2-SNAPSHOT
[WARNING] 'parent.relativePath' of POM io.katharsis:katharsis-parent:2.8.2-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml) points at io.katharsis:katharsis-build instead of org.sonatype.oss:oss-parent, please verify your project structure @ io.katharsis:katharsis-parent:2.8.2-SNAPSHOT, /home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml, line 68, column 13
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.katharsis:katharsis-client:bundle:2.8.2-SNAPSHOT
[WARNING] 'parent.relativePath' of POM io.katharsis:katharsis-parent:2.8.2-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml) points at io.katharsis:katharsis-build instead of org.sonatype.oss:oss-parent, please verify your project structure @ io.katharsis:katharsis-parent:2.8.2-SNAPSHOT, /home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml, line 68, column 13
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.katharsis:katharsis-jpa:bundle:2.8.2-SNAPSHOT
[WARNING] 'parent.relativePath' of POM io.katharsis:katharsis-parent:2.8.2-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml) points at io.katharsis:katharsis-build instead of org.sonatype.oss:oss-parent, please verify your project structure @ io.katharsis:katharsis-parent:2.8.2-SNAPSHOT, /home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml, line 68, column 13
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.katharsis:katharsis-validation:bundle:2.8.2-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: javax:javaee-api:jar -> duplicate declaration of version ${javaee-api.version} @ io.katharsis:katharsis-validation:[unknown-version], /home/travis/build/katharsis-project/katharsis-framework/katharsis-validation/pom.xml, line 77, column 15
[WARNING] 'parent.relativePath' of POM io.katharsis:katharsis-parent:2.8.2-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml) points at io.katharsis:katharsis-build instead of org.sonatype.oss:oss-parent, please verify your project structure @ io.katharsis:katharsis-parent:2.8.2-SNAPSHOT, /home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml, line 68, column 13
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.katharsis:katharsis-brave:bundle:2.8.2-SNAPSHOT
[WARNING] 'parent.relativePath' of POM io.katharsis:katharsis-parent:2.8.2-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml) points at io.katharsis:katharsis-build instead of org.sonatype.oss:oss-parent, please verify your project structure @ io.katharsis:katharsis-parent:2.8.2-SNAPSHOT, /home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml, line 68, column 13
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.katharsis:katharsis-ui:jar:2.8.2-SNAPSHOT
[WARNING] 'parent.relativePath' of POM io.katharsis:katharsis-parent:2.8.2-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml) points at io.katharsis:katharsis-build instead of org.sonatype.oss:oss-parent, please verify your project structure @ io.katharsis:katharsis-parent:2.8.2-SNAPSHOT, /home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml, line 68, column 13
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Katharsis parent POM
[INFO] katharsis-core
[INFO] katharsis-rs
[INFO] io.katharsis:katharsis-servlet
[INFO] katharsis-cdi
[INFO] katharsis-spring
[INFO] katharsis-vertx
[INFO] katharsis-client
[INFO] katharsis-jpa
[INFO] katharsis-validation
[INFO] katharsis-brave
[INFO] katharsis-examples
[INFO] Katharsis Dropwizard + MongoDB Example
[INFO] Katharsis Jersey Example
[INFO] Katharsis Simple Dropwizard Example
[INFO] Katharsis Wildfly Example
[INFO] Spring Boot Simple Example
[INFO] Katharsis Vertx Simple Example
[INFO] katharsis-ui
[INFO] Katharsis build POM
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Katharsis parent POM 2.8.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ katharsis-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ katharsis-parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ katharsis-parent ---
[INFO] Installing /home/travis/build/katharsis-project/katharsis-framework/katharsis-parent/pom.xml to /home/travis/.m2/repository/io/katharsis/katharsis-parent/2.8.2-SNAPSHOT/katharsis-parent-2.8.2-SNAPSHOT.pom
[INFO] 
[INFO] --- maven-deploy-plugin:2.8.2:deploy (default-deploy) @ katharsis-parent ---
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/katharsis/katharsis-parent/2.8.2-SNAPSHOT/maven-metadata.xml
605/605 B   
            
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/katharsis/katharsis-parent/2.8.2-SNAPSHOT/maven-metadata.xml (605 B at 0.7 KB/sec)
Uploading: https://oss.sonatype.org/content/repositories/snapshots/io/katharsis/katharsis-parent/2.8.2-SNAPSHOT/katharsis-parent-2.8.2-20161216.153154-3.pom
2/15 KB     
4/15 KB   
6/15 KB   
8/15 KB   
10/15 KB   
12/15 KB   
14/15 KB   
15/15 KB   
           
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Katharsis parent POM ............................... FAILURE [  2.053 s]
[INFO] katharsis-core ..................................... SKIPPED
[INFO] katharsis-rs ....................................... SKIPPED
[INFO] io.katharsis:katharsis-servlet ..................... SKIPPED
[INFO] katharsis-cdi ...................................... SKIPPED
[INFO] katharsis-spring ................................... SKIPPED
[INFO] katharsis-vertx .................................... SKIPPED
[INFO] katharsis-client ................................... SKIPPED
[INFO] katharsis-jpa ...................................... SKIPPED
[INFO] katharsis-validation ............................... SKIPPED
[INFO] katharsis-brave .................................... SKIPPED
[INFO] katharsis-examples ................................. SKIPPED
[INFO] Katharsis Dropwizard + MongoDB Example ............. SKIPPED
[INFO] Katharsis Jersey Example ........................... SKIPPED
[INFO] Katharsis Simple Dropwizard Example ................ SKIPPED
[INFO] Katharsis Wildfly Example .......................... SKIPPED
[INFO] Spring Boot Simple Example ......................... SKIPPED
[INFO] Katharsis Vertx Simple Example ..................... SKIPPED
[INFO] katharsis-ui ....................................... SKIPPED
[INFO] Katharsis build POM ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.706 s
[INFO] Finished at: 2016-12-16T15:31:54+00:00
[INFO] Final Memory: 21M/491M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project katharsis-parent: Failed to deploy artifacts: Could not transfer artifact io.katharsis:katharsis-parent:pom:2.8.2-20161216.153154-3 from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/io/katharsis/katharsis-parent/2.8.2-SNAPSHOT/katharsis-parent-2.8.2-20161216.153154-3.pom. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by chb0github** [comment]
This looks familiar. I will see what I can do.

**Comment by chb0github** [comment]
BTW: Can we have this on a seperate branch -- the development branch is no longer the default

**Comment by robertgrabowski** [comment]
Note: It still seems to me that none of this `mvn install/deploy` stuff is supposed to be executed in the first place when building a pull request. After all, a pull request is by definition not yet merged into the main katharsis repo, so I guess you wouldn't want the build artifact of the pull request to be published as an official katharsis build anywhere. I suppose that's why there's this condition in `build.sh`:
```
if [ "${TRAVIS_PULL_REQUEST}" != "true" ]
```
But this won't work, because the value of TRAVIS_PULL_REQUEST is never `true`, but the pull request number (or `false` when not building a pull request).

**Comment by chb0github** [comment]
I removed it. Only master is a protected branch and I removed the whole
script.

**Pull request merged**
