### PR TITLE
#299 Add new annotation JsonApiRelation

### PR DESCRIPTION
**Pull request by mitch2na**

### CODE REVIEW

**Comment by chb0github** [comment]
I have to get with @masterspambot before I can go anywhere with this PR.

We now have 2 changes that I would only feel comfortable with in 3.0 and I currently can't release

**Comment by mitch2na** [comment]
@chb0github Yeah i wanted to get this into 3.0 since it simplifies the relationship annotation.

**Comment by mohlek** [comment]
Love it :)

**Comment by remmeier** [comment]
can the various PRs be merged (https://gitter.im/katharsis-project)? I have some more things, but I'm currently blocked by the ones already in progress. After those here it should be ready for 3.0.

**Comment by remmeier** [comment]
merged into develop_v3 branch to prepare for v3 release. Later develop will be updated as well.

**Pull request closed without merging**
