### PR TITLE
#283 Adds -Xdoclint:none additionalparam to maven-javadoc-plugin

### PR DESCRIPTION
**Pull request by Sandmania**
This change will add -Xdoclint:none as an additionalparam to maven-javadoc-plugin, if jdk 1.8 is used. The param addition is controlled by maven profile, which is activated if jdk1.8 >= is used.

### CODE REVIEW

**Comment by Sandmania** [comment]
The linter issues can sill be seen as warnings in the build log:

```
[WARNING] /Users/jounilatvatalo/hobby/codebase/katharsis-framework/katharsis-core/src/main/java/io/katharsis/repository/ResourceRepositoryBase.java:21: warning - Tag @link: can't find delete(Object) in io.katharsis.repository.ResourceRepositoryBase
```

**Comment by chb0github** [comment]
Lol! 

Everyone hates poor lombok. How about we just start using kotlin :-)

It looks like we would need to drive this config via profile. Maybe I am mistaken.

**Comment by chb0github** [comment]
Yes, that is what I meant. When we move to 1.8 I will need to update the
maven build to now include a profile. Our javadoc isn't up to par

**Comment by chb0github** [comment]
Resync this and lets merge

**Comment by Sandmania** [comment]
Done, I guess? :) Still new to github workflow.

**Pull request merged**
