### PR TITLE
#262 FieldResourceGet should not assume existence of JsonApiResource annotation

### LINKED ISSUE #262: FieldResourceGet assumes existence of JsonApiResource annotation
PR #226  introduced a bug in `FieldResourceGet`. It assumes that resources always have a `JsonApiResource` which is not the case.

### PR DESCRIPTION
**Pull request by Ramblurr**
fixes #262

### CODE REVIEW

**Comment by remmeier** [comment]
There is already a pr for this.

**Comment by remmeier** [comment]
4 Days ago by me

**Comment by Ramblurr** [comment]
*sigh* I should have seen that. Closing in favor of @remmeier 's #256

**Comment by remmeier** [comment]
I guess we should make sure PRs get applied quickly to make sure we do not duplicate efforts :-(

**Pull request closed without merging**
