### PR TITLE
katharsis 3.0 update of develop branch

### PR DESCRIPTION
**Pull request by remmeier**

### CODE REVIEW

**Comment by mohlek** [comment]
Fixed a few bugs as stated in sonar. https://github.com/katharsis-project/katharsis-framework/pull/338

**Comment by chb0github** [comment]
we can just merge right into master.

**Comment by remmeier** [comment]
ok, I changed to master and resolved all the conflicts. We probably should do some house keeping of the branches once all of them are merged. I can do that.

one thing I had a collision between the two branches: I currently left the java source compatiblity on java 7. There were two requests from new projects the past weeks to keep supporting it for a little while longer (two, three months). So I think it makes sense to at least release the current version this way since it does not use of any new features. We can also start using Java 8 API where needed. Or make use of Lambdas, etc. in test cases. And should we need anything more, we can change the source compatiblity back again. I tought for today the community growth seems more important.

**Comment by remmeier** [comment]
some npm installation errors, i guess the infrastructure recovers at some point, otherwise katharsis-ui can also be excluded in the root pom

**Pull request merged**
