### PR TITLE
Package refactoring

### PR DESCRIPTION
**Pull request by remmeier**

### CODE REVIEW

**Comment by remmeier** [comment]
a wide varierty of things are now cleaned up. 

- all that is intended to be removed in the future is still there and functional, but deprecated and moved to a "legacy" package to have a cleaner api otherwise. Setting up a katharsis-core-legacy for a cleaner separation would take a bit to much time.
- no class name changes, so fixing the imports suffices to have it running again.
- the main things are still in there place

**Comment by remmeier** [comment]
deprecation and restructuring is intertwined, there is not really a split.

**Comment by remmeier** [comment]
The commits can be squashed on merge. There is only moving around. No significant code changes except making use of ResourceInformation instead of Class/Field at some places to clean up the public api. 

I would suggest to just look at the structure, i.e. package naming and location of the classes.

**Comment by remmeier** [comment]
things can also be moved around further, Just a first propsal...

**Comment by chb0github** [comment]
@remmeier it would be much better to only submit PR when you believe them ready to be merged. 587 files I can't look through - I assume it's just a whole bunch of file reshuffling. 

Are we ready to move forward with 3.0 @masterspambot @remmeier ?

**Comment by remmeier** [comment]
yes, plenty of reshuffling. Just looking at the package contents suffices as review.

**Comment by remmeier** [comment]
so?

**Comment by chb0github** [comment]
Sorry I forgot to follow up

**Comment by remmeier** [comment]
thx!

**Comment by chb0github** [comment]
in these 587 files, as I got to do a final build before 3.0, I noticed that there are changelog.md files that are redundant with the one in the root directory. These get auto-generated with the build and there is one at the root level so it's visible on the main page. I didn't catch it in this gargantuan review.

**Pull request merged**
