### PR TITLE
Show friendly error and prevent NPE when setting invalid QuerySpec options in katharsis boot

### PR DESCRIPTION
**Pull request by Ramblurr**
see #373

### CODE REVIEW

**Comment by chb0github** [comment]
Master branch needs to be in a buildable state before we can merge.

**Comment by Ramblurr** [comment]
I can't see how this broke the build. Looking [at the Travis log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/212946517/log.txt) I don't see anything that could be related to this PR.

```
[INFO] Downloading: https://repository.apache.org/releases/org/springframework/security/spring-security-bom/4.0.3.RELEASE/spring-security-bom-4.0.3.RELEASE.pom
[ERROR] The build could not read 12 projects -> [Help 1]
[ERROR]   
[ERROR]   The project io.katharsis:katharsis-core:3.0.1-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-core/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.3 or one of its dependencies could not be resolved: Could not transfer artifact org.osgi:org.osgi.core:jar:4.3.1 from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
[ERROR]     Unknown packaging: bundle @ line 12, column 16
[ERROR]   
[ERROR]   The project io.katharsis:katharsis-test:3.0.1-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-test/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.3 or one of its dependencies could not be resolved: Could not transfer artifact org.osgi:org.osgi.core:jar:4.3.1 from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
[ERROR]     Unknown packaging: bundle @ line 12, column 16
[ERROR]   
[ERROR]   The project io.katharsis:katharsis-rs:3.0.1-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-rs/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.3 or one of its dependencies could not be resolved: Could not transfer artifact org.osgi:org.osgi.core:jar:4.3.1 from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
[ERROR]     Unknown packaging: bundle @ line 12, column 16
[ERROR]   
[ERROR]   The project io.katharsis:katharsis-servlet:3.0.1-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-servlet/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.3 or one of its dependencies could not be resolved: Could not transfer artifact org.osgi:org.osgi.core:jar:4.3.1 from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
[ERROR]     Unknown packaging: bundle @ line 15, column 16
[ERROR]   
[ERROR]   The project io.katharsis:katharsis-cdi:3.0.1-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-cdi/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.3 or one of its dependencies could not be resolved: Could not transfer artifact org.osgi:org.osgi.core:jar:4.3.1 from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
[ERROR]     Unknown packaging: bundle @ line 14, column 14
[ERROR]   
[ERROR]   The project io.katharsis:katharsis-spring:3.0.1-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-spring/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.3 or one of its dependencies could not be resolved: Could not transfer artifact org.osgi:org.osgi.core:jar:4.3.1 from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
[ERROR]     Unknown packaging: bundle @ line 13, column 16
[ERROR]   
[ERROR]   The project io.katharsis:katharsis-client:3.0.1-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-client/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.3 or one of its dependencies could not be resolved: Could not transfer artifact org.osgi:org.osgi.core:jar:4.3.1 from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
[ERROR]     Unknown packaging: bundle @ line 12, column 13
[ERROR]   
[ERROR]   The project io.katharsis:katharsis-meta:3.0.1-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-meta/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.3 or one of its dependencies could not be resolved: Could not transfer artifact org.osgi:org.osgi.core:jar:4.3.1 from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
[ERROR]     Unknown packaging: bundle @ line 12, column 13
[ERROR]   
[ERROR]   The project io.katharsis:katharsis-jpa:3.0.1-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-jpa/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.3 or one of its dependencies could not be resolved: Could not transfer artifact org.osgi:org.osgi.core:jar:4.3.1 from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
[ERROR]     Unknown packaging: bundle @ line 13, column 14
[ERROR]   
[ERROR]   The project io.katharsis:katharsis-validation:3.0.1-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-validation/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.3 or one of its dependencies could not be resolved: Could not transfer artifact org.osgi:org.osgi.core:jar:4.3.1 from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
[ERROR]     Unknown packaging: bundle @ line 12, column 13
[ERROR]   
[ERROR]   The project io.katharsis:katharsis-brave:3.0.1-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-brave/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.3 or one of its dependencies could not be resolved: Could not transfer artifact org.osgi:org.osgi.core:jar:4.3.1 from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
[ERROR]     Unknown packaging: bundle @ line 12, column 14
[ERROR]   
[ERROR]   The project io.katharsis:katharsis-security:3.0.1-SNAPSHOT (/home/travis/build/katharsis-project/katharsis-framework/katharsis-security/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.3 or one of its dependencies could not be resolved: Could not transfer artifact org.osgi:org.osgi.core:jar:4.3.1 from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out (Connection timed out) -> [Help 2]
[ERROR]     Unknown packaging: bundle @ line 13, column 13
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

[31;1mThe command "eval mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V " failed. Retrying, 2 of 3.[0m

```

Possibly Travis' network had an outage during the build.

**Comment by chb0github** [comment]
I will see if I can restart the build. I had the same thought. My question
about the use of npm remains

**Comment by Ramblurr** [comment]
Thanks @chb0github

**Pull request merged**
