### PR TITLE
Module API to allow to extend core katharsis functionality #45

### PR DESCRIPTION
**Pull request by remmeier**
- implementation similar to Jackson module implementation
- Module interface that provides hooks into Katharsis
- Currently supports to add:
 - repositories
 - exception mappers
 - filters
 - jackson modules
 - information builders
- CoreModule provides current Katharsis functionality
- initial implementation
 - only a minimal set of classes touched
 - future extensions possible
 - CoreModule might grow a bit
 - the use of internal packages should be considered in the future
within Katharsis-core to declare what API is accessible to modules.
- SimpleModule implementation has a starting point to write own modules
- ModuleRegistry as container to hold all modules
- Spring, Servlet, JAX-RS implementations updated and support new method
"addModule(Module)".

### CODE REVIEW

**Comment by remmeier** [comment]
disclaimer:  last major PR for katharsis-core (and rs/servlet/...) from my side. Gives the necessary flexiblity to implement new modules to extend katharsis-core.  katharsis-client, katharsis-jpa and kanatharsis-validation would be three such projects currently in preparation.

**Comment by remmeier** [comment]
looks like a build server setup issue:

 Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project katharsis-parent: Failed to deploy artifacts: Could not transfer artifact io.katharsis:katharsis-parent:pom:2.6.0-20160817.110340-11 from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/io/katharsis/katharsis-parent/2.6.0-SNAPSHOT/katharsis-parent-2.6.0-20160817.110340-11.pom. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]

**Comment by remmeier** [comment]
should not do a deploy

**Comment by meshuga** [comment]
Should not. https://github.com/katharsis-project/katharsis-framework/blob/develop/build.sh is not recognizing PRs properlyy.

**Comment by meshuga** [comment]
I added a hack to improve checking if it's a PR (https://github.com/katharsis-project/katharsis-framework/commit/8ea0d135ba20f2ae70a5d22ad9156a19c910f0a0). Could you merge with develop to test it?

**Comment by remmeier** [comment]
I closed and reopened to trigger the build again. That did not work. Was that supposed to be work? or can I do something else?

**Comment by meshuga** [comment]
Could you merge your branch with develop? The change couldn't be applied because adnovum:module has old building script.

**Comment by ieugen** [comment]
@meshuga I have merged master into develop to make them close as a code base.

**Comment by remmeier** [comment]
I think I got it merged, but the issue seem to persist. On the positive side the katharsis coverage just got green :-)

**Comment by meshuga** [comment]
see #86

**Pull request closed without merging**
