### PR TITLE
added a quick and dirty test for lazy relations

### PR DESCRIPTION
**Pull request by mohlek**
Just a quick and dirty test for lazy relations

Since Katharsis 2.7+ lazy relations are not working probably.
Currently (2.8.1) im not able to have current situation:

```java

@Data
@JsonApiResource(type = "foo")
public class foo {
    @JsonApiId
    @Column
    private Long id;
    @Column
    private Boolean active;
    @JsonApiToOne(lazy = true)
    private Bar bar;
}
```

```java

@Data
@JsonApiResource(type = "bar")
public class Bar {
    @JsonApiId
    @Column
    private Long id;
    @Column
    private String stuff;
}
```

having bar = null results in 

```JSON
{  
   "data":[  
      {  
         "type":"foo",
         "id":"1",
         "attributes":{  
            "active":true
         },
         "relationships":{  
            "bar":{  
               "links":{  
                  "self":"/foo/1/relationships/bar",
                  "related":"/foo/1/bar"
               }
            }
         },
         "links":{  
            "self":"/foo/1"
         }
      }
   ]
}
```

requesting `/foo/1/bar` results in an error

```curl
curl 'http://api.xxx/foo/1/bar' -H 'Pragma: no-cache' -H 'Origin: http://127.0.0.1:4200' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4' -H 'Authorization: Bearer 7f6a82dc-f5d4-428e-af87-f8632cb1cfc9' -H 'Accept: application/vnd.api+json' -H 'Cache-Control: no-cache' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36' -H 'Connection: keep-alive' -H 'Referer: http://127.0.0.1:4200/' -H 'DNT: 1' --compressed -v
* About to connect() to api.xxx port 80 (#0)
*   Trying 127.0.0.1...
* Connected to api.xxx (127.0.0.1) port 80 (#0)
> GET /foo/1/bar HTTP/1.1
> Host: api.localdev
> Pragma: no-cache
> Origin: http://127.0.0.1:4200
> Accept-Encoding: gzip, deflate, sdch
> Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
> Authorization: Bearer 7f6a82dc-f5d4-428e-af87-f8632cb1cfc9
> Accept: application/vnd.api+json
> Cache-Control: no-cache
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36
> Connection: keep-alive
> Referer: http://127.0.0.1:4200/
> DNT: 1
> 
< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.10.1
< Date: Mon, 21 Nov 2016 11:12:41 GMT
< Content-Length: 0
< Connection: keep-alive
< X-Powered-By: Undertow/1
< Access-Control-Allow-Headers: X-Requested-With,Content-Type,Authorization,X-Test
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Methods: GET, POST, PATCH, DELETE, OPTIONS
< 
* Connection #0 to host api.xxx left intact
```

```
12:14:32,546 ERROR [io.katharsis.dispatcher.RequestDispatcher] (default task-2) failed to process request: io.katharsis.resource.exception.init.ResourceNotFoundInitializationException: Resource of class not found: org.ddg.DDGRestAPI.model.prod.Bar
	at io.katharsis.resource.registry.ResourceRegistry.getEntry(ResourceRegistry.java:106)
	at io.katharsis.resource.registry.ResourceRegistry.getEntry(ResourceRegistry.java:94)
	at io.katharsis.queryspec.internal.QueryParamsAdapterBuilder.build(QueryParamsAdapterBuilder.java:24)
	at io.katharsis.dispatcher.RequestDispatcher.dispatchRequest(RequestDispatcher.java:75)
	at io.katharsis.rs.KatharsisFilter.dispatchRequest(KatharsisFilter.java:144)
	at io.katharsis.rs.KatharsisFilter.filter(KatharsisFilter.java:111)
	at org.ddg.DDGRestAPI.service.auth.AuthenticationFilter.filter(AuthenticationFilter.java:121)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:140)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:197)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

12:14:32,546 ERROR [io.katharsis.rs.KatharsisFilter] (default task-2) failed to dispatch request: io.katharsis.resource.exception.init.ResourceNotFoundInitializationException: Resource of class not found: org.ddg.DDGRestAPI.model.prod.Bar
	at io.katharsis.resource.registry.ResourceRegistry.getEntry(ResourceRegistry.java:106)
	at io.katharsis.resource.registry.ResourceRegistry.getEntry(ResourceRegistry.java:94)
	at io.katharsis.queryspec.internal.QueryParamsAdapterBuilder.build(QueryParamsAdapterBuilder.java:24)
	at io.katharsis.dispatcher.RequestDispatcher.dispatchRequest(RequestDispatcher.java:75)
	at io.katharsis.rs.KatharsisFilter.dispatchRequest(KatharsisFilter.java:144)
	at io.katharsis.rs.KatharsisFilter.filter(KatharsisFilter.java:111)
	at org.ddg.DDGRestAPI.service.auth.AuthenticationFilter.filter(AuthenticationFilter.java:121)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:140)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:197)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

12:14:32,547 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-2) RESTEASY002010: Failed to execute: javax.ws.rs.WebApplicationException: HTTP 500 Internal Server Error
	at io.katharsis.rs.KatharsisFilter.filter(KatharsisFilter.java:117)
	at org.ddg.DDGRestAPI.service.auth.AuthenticationFilter.filter(AuthenticationFilter.java:121)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:140)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:197)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.katharsis.resource.exception.init.ResourceNotFoundInitializationException: Resource of class not found: org.ddg.DDGRestAPI.model.prod.Bar
	at io.katharsis.resource.registry.ResourceRegistry.getEntry(ResourceRegistry.java:106)
	at io.katharsis.resource.registry.ResourceRegistry.getEntry(ResourceRegistry.java:94)
	at io.katharsis.queryspec.internal.QueryParamsAdapterBuilder.build(QueryParamsAdapterBuilder.java:24)
	at io.katharsis.dispatcher.RequestDispatcher.dispatchRequest(RequestDispatcher.java:75)
	at io.katharsis.rs.KatharsisFilter.dispatchRequest(KatharsisFilter.java:144)
	at io.katharsis.rs.KatharsisFilter.filter(KatharsisFilter.java:111)
	... 44 more

```

### CODE REVIEW

**Comment by mohlek** [comment]
Note: This test is supposed to fail! It covers a bug in Katharsis.

**Comment by remmeier** [comment]
I updated the test case. findOneTarget was looking for the id, not for an actual relation. I don't assume that this was supposed to be this way.

	relRepoLazy.findOneTarget(1L, "lazyProject", new QueryParams());

instead of

relRepoLazy.findOneTarget(1L, "id", new QueryParams());

then the test does not give any errors

**Comment by remmeier** [comment]
or should it give one?

**Comment by mohlek** [comment]
good questions. Im not familiar with the katharsis client.

I just want to get my resource from `/foo/1/bar`, which results in an error

**Comment by remmeier** [comment]
which one do you mean? when you use "id" to make the call to findTarget? or with "lazyProject" (my change)?

**Comment by remmeier** [comment]
can you update the test? I can then take another look.

**Comment by mohlek** [comment]
@remmeier updated description

**Comment by mohlek** [comment]
omg .. I found it. Katharsis > 2.6.0 seems to NEED a ResourceRepository.

I just had a RelationshipRepository defined which worked pretty well.

**Comment by remmeier** [comment]
I guess that would be use case we should support (and test)

**Comment by mohlek** [comment]
I think the bugs is deep inside. Today i hunted a bug where a entity wouldn't serialize at all. It seems that as soon you define a relationship katharsis requires a entity repository. In Katharsis 2.6 I could define a relationship, add `@JsonApiIncludeByDefault`, fill the entity and was done.

`RelationshipContainerSerializer.java:110`
```Java
        gen.writeStartArray();
        if (targetDataObjects != null) {
            for (Object targetDataObject : (Iterable) targetDataObjects) {
                Class<?> targetDataObjClass = resourceRegistry.getResourceClass(targetDataObject).get();
                gen.writeObject(new LinkageContainer(targetDataObject, targetDataObjClass, resourceRegistry.getEntry(targetDataObject)));
            }
        }
```

resourceRegistry doesn't contain my entity as i didn't provided an own repository. I guess this bug is related.

Maybe we should discus this at a different issue as this gets offtopic?!

@masterspambot Any idea?

**Pull request closed without merging**
