### PR TITLE
#238 How to use katharsis with springboot and jpa?

### PR DESCRIPTION
**Pull request by remmeier**
updated spring example:

- added validation, brave and jpa module
- added an entity
- added new exception mapper example
- validation exception handling now done by validation module
- minor api improvement for QuerySpec.apply
- added TransactionRunner implementation to katharsis-spring to ease setup
- added Katharsis client example
- JPA DTO mapping example
- JPA computed attribute example
- logback setup including configuration for zipkin/brave

### CODE REVIEW

**Comment by remmeier** [comment]
it would be good if somebody with Spring Boot knowledge has a quick look at it. I guess the JPA setup can be simplified (it is currently more of a plain Spring setup).

**Comment by Ramblurr** [comment]
A few comments on the JpaConfig:


1. Why do you need to explicitly create the `sessionFactory` and `dataSource`? Generally in spring boot those are provided automatically unless there is non-standard configuration required.
2. `hibernateProperties`: setting these in java isn't the spring-boot "way", these should be specified in an `application.properties` file if they are runtime/general values, or a `application-test.properties` file for testing.

Actually I think that entire configuration class can be removed, and replaced with a few properties. There's no need to specify the model packages to scan, as the `@SpringBootApplication` will automatically pick them up since they are under it.

**Comment by remmeier** [comment]
no, I so far I just used plain Spring, no Spring boot.

**Comment by remmeier** [comment]
done, thx

**Comment by remmeier** [comment]
makes perfect sense, I will add those in the next round.

**Pull request merged**
