### PR TITLE
#229 Support to differentiate between patch and post on the server side

### PR DESCRIPTION
**Pull request by remmeier**
Since we cannot change the existing internface without backward
compatiblity, to new interfaces will be introduced:

- ResourceRepositoryV2
- RelationshipRepositoryV2

extending the current QuerySpecRepository, providing a new method create(...) and also make use of the new ResourceList.

The current ResourceRepositoryBase and RelationshipRepositoryBase are updated accordingly to also implement the new interface.

katharsis-client is updated accordingly and with this commit no longer consider to be experimental.

### CODE REVIEW

**Comment by mohlek** [comment]
Why not Release with v3?
I dont like having classXYZ2 classXYZ5 and so on. That's confusing at some point.
Will the old one always be available and supported?

**Comment by mohlek** [comment]
With a major release we can and should break interfaces.

**Comment by remmeier** [comment]
I don't like the V2 either. But I don't like long names like "QuerySpec"ResourceRepepository. But compared to the ResourceRepository it breaks a number of things:

- ResourceList return type giving access to meta data and links
- QuerySpec instead of QueryParams
- create(...)

This are quite substantial changes and I think we must support QueryParams for quite a while.
Considering all this, "V2" feels like being the best option.

How about a 2.9 release soon with all we have? And more documentation. Then we could have a look at

https://github.com/katharsis-project/katharsis-framework/issues/210

And cleanup the packages (which is "slightly" breaking and 3.0). The important things like the repositories, annotations, etc. would stay at the same place.

With a katharsis 4.0 sometimes in a year or so we could start removing deprecated things?

**Comment by remmeier** [comment]
In general I think we should never introduce real breaking changes with a major release, just throw out deprecated stuff to make the transition as smoth as possible,

**Comment by Ramblurr** [comment]
What happens when the next major version is released and the "V1" is deprecated? Then there will only be `RelationshipRepositoryV2` but no `RelationshipRepository` correct?

**Comment by remmeier** [comment]
I would do a two step migration:

- deprecate ResourceRepository with Katharsise 3.0
- reintroduce ResourceRepository (extending RepositoryRepositoryV2) in Katharsis 4.0
- deprecate ResourceRepositoryV2 in Katharsis 4.0

Personally, I would be perfectly fine replacing the old interfaces, I have already migrated. But it is a gigantic change (most notably QueryParams vs QuerySpec) and I think we have to give people some time to do this update. They may want to do this incrementally, starting with a first repository to check everything out.

last time I have seen a project doing a real major break (ng2, python), it did not end particularly well. That's why I try to stay on the safe side with backward compatiblity to not alienate anyone.

**Comment by remmeier** [comment]
but we can also ask the community of course

**Comment by chb0github** [comment]
I agree with you Maurice. I am starting to feel like 3.0 needs to be a
complete redo

**Comment by Sandmania** [comment]
I don't see why 3.0 _should_ or _needs_ to be or do anything.

We have been using Katharsis since 0.9.x and the easier the migration between versions the more likely it is for us (and I dare to suggest that for many others) to take the newer versions to use. Refactoring all repositories at this point is by no means impossible, but I would like to see a two step migration where our existing repositories wouldn't break but our new repositories could benefit from the new model.

I don't quite understand what is thought as the biggest issue with the gradual deprecation? Is it the naming that is thought to cause confusion?

**Comment by chb0github** [comment]
Gradual deprecation means a constant eye toward backward compatibility and
sometimes intentionally maintaining bad ideas. But, if we totally walk away
from what we have, no one will take it up. The way Repositories and created
and managed is just way too much work. Tedious work at that. A change is
about making things for new developers easier.

**Comment by Ramblurr** [comment]
For me the naming issue and gradual deprecation is fine. Refactoring the name of the repositories is doable. I also support @chb0github's  view too.

Internal changes code refactorings aren't dealbreakers, and whatever the community decides we can go along with.

I'm _much more concerned_ with the QueryParams -> QuerySpec migration, as that entails external changes. Clients consuming our katharsis API are already using the QueryParams serialization format, so we can't  replace it with QuerySpec.

We need a real migration plan from QueryParams to QuerySpec, that includes support for BOTH serialization formats for some time. Once we have that we can introduce QuerySpec and deprecate the old style serializations, and after our clients have updated or after some reasonable time, only use the new format.

**Comment by remmeier** [comment]
regarding the migration, there are two things:
- QuerySpec vs QueryParams usage in the repositories
- the serialization format (e.g. "sort[type][attr]=desc" vs "sort=-attr")

Currently there is a QueryParams to QuerySpec converter, meaning people can start using QuerySpec in a QueryParams environment. 

At some point the serialization format needs to be switched. I guess there some more backward compatibility in the new serializer would be possible (allowing to handle "sort[type][attr]"). Then the migration should be fairly smooth.

**Comment by Ramblurr** [comment]
Oh that is good news! Can you point me to where I can see an example of that?

**Comment by remmeier** [comment]
The conversion happens in RepositoryRequestSpecImpl.getQuerySpec(...). 

katharsis-client has a mixed setup. The ProjectRepository still makes use of QueryParams. The others QuerySpec. There is a QuerySpecClientTest and a QueryParamsClientTest accessing those repositories. By default the server still runs on QueryParams. The TestApplication class takes a boolean argument which one to use.

I updated the documentation a bit to clarify what I mentioned in the previous post.

**Comment by Ramblurr** [comment]
@remmeier Is this possible when using the `@JsonApiResourceRepository` annotation? We use that pretty much exclusively.

**Pull request merged**
